#!/bin/bash

HISTORY=~/.surf/history
NITEMS=15

# XXX needs some clean up
hist() {
	[ -z "$1" ] && return
	q="$1"
	exists="$(cut -d' ' -f2- "$HISTORY" |grep -xc "$q")"
	if [ "$exists" -eq 0 ]; then
		echo "0|${q}" >> "$HISTORY"
	else
		u="$q"
		q="$(echo "$q" |sed 's,\([/]\),\\\1,g')"
		n="$(sed -n "s/^\([0-9]*\) ${q}$/\1/p" "$HISTORY")"
		n="$(echo $n+1|bc)"
		sed -i "s/^\([0-9]*\) ${q}/${n} ${q}/" "$HISTORY"
	fi
}

getquery() {
	cat "$HISTORY" |sort -rn | cut -d' ' -f2- | dmenu -i -l "$NITEMS"
}

goto() {
	xid="$1"
	prop="$2"
	uri="$3"
	xprop -id "$xid" -f "$prop" 8s -set "$prop" "$uri"
}

urlencode() {
	printf %s "$1" | od -t x1 -An | tr -d '\n' | tr ' ' '%'
}

main() {
	xid="$1"
	prop="$2"
	q="$(getquery)"
	[ -z "$xid" -o -z "$prop" -o -z "$q" ] && exit 1

	# If starts with '#', then don't put into history (and removes the '#')
	if [ "$(echo $q |cut -b1)" = "#" ]; then
		q="$(echo "$q" |cut -b2-)"
	else
		hist "$q"
	fi

	# XXX URIs in history has already been check so can be skipped here.

	host="$(echo $q |cut -d/ -f3)"
	search="$(host -4t A "$host" > /dev/null; echo $?)"
	if [ "$search" -ne 0 ]; then
		# enjoy !bangs
		uri="https://duckduckgo.com/?q="
		uri+="$(urlencode "$q")"
	else
		uri="$q"
	fi
	goto "$xid" "$prop" "$uri"
}

main "$@"
